# 目录管理
---
- hosts: all
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /tmp/test
        state: directory
        mode: '0755'

    - name: 删除一个目录
      file:
        path: /tmp/test
        state: absent

# 文件管理
---
- hosts: all
  tasks:
    - name: 创建文件
      path: /tmp/test.txt
      state: touch
      mode: '0755'
    - name: 删除文件
      path: /tmp/test.txt
      state: absent
      